### ISSUE TITLE
PayableBy in payment section / my pull request

### ISSUE THREAD

**Issue by david-schnepf** [bbitgmbh/bbit.swiss-qr-bill#128]
Hello,

I just realize that my pull request logically didn't pass tests because reference picture do not contains the added PayableBy part...

My change should be easy to merge since it is in fact a single line of code

Thx!

**Comment by thegnuu** [comment]
@david-schnepf thank you for your enhancement and sorry for my delayed answer, for some reason i missed the notifications.

I just merged your changes manually to master and optimized the test threshold a little bit, because the output on ubuntu seems to be slightly different from the one on MacOS. I am enhancing the GitHub actions at the moment to run all tests on multiple nodejs versions, but I will release a new version today!

**Comment by david-schnepf** [comment]
Very good news, thanks !

**Comment by thegnuu** [comment]
`v0.1.4` should be good to go. I hope I did not mess anything up with the workflow changes :)
