### ISSUE TITLE
npm package version

### ISSUE THREAD

**Issue by david-schnepf** [bbitgmbh/bbit.swiss-qr-bill#130]
Not really an issue but we are here at v1.0.4 and npm install still provide v1.0.2, what is the usual delay of propagation ?

Besides, is there a way to track directly latest version here instead ?

Sorry if this is a little bit silly and/or makes no sens but... I'm a beginner...

Thanks!

**Comment by thegnuu** [comment]
Hi @david-schnepf,

The package is currently only published to GitHub packages, since we moved all our company related packages to GitHub. I will have a look at this next week, should be easy to publish it to both, GitHub packages and npm.

Sorry, I was not realizing this since yarn is configured on my client to fetch our prefixed packages directly from GitHub :)

I'll let you know as soon I updated the CI.

**Comment by thegnuu** [comment]
@david-schnepf I tried to add a description how to config npm use GitHub Packages for our `@bbitgmbh` packages, unfortunately I realized that GitHub Packages, even if they are public, cannot be fetched without authentication which makes this product basically useless for open source projects 🤷🏼‍♂️

Anyway, I now deprecated the old module `@bbit/swiss-qr-bill` on npm and optimized the CI to publish to both, GitHub and npm. You should now be able to use the package `@bbitgmbh/bbit.swiss-qr-bill` and the releases should not be delayed in future.

Took me like 2 hours because of some weird issues with publishing it, but it should now work :)

Can you please check it and close this issue if everything is okay?

**Comment by david-schnepf** [comment]
as far as I can test it just works like a charm by using @bbitgmbh/bbit.swiss-qr-bill in place of @bbit/swiss-qr-bill :-)

Thanks a lot !
