### ISSUE TITLE
Broken swiss cross image

### ISSUE THREAD

**Issue by thibaultM42** [bbitgmbh/bbit.swiss-qr-bill#158]
Hello, 
First of all thanks for this great project!
I'm just using the QRCode generation part, not the entire QRSlip, but as I was testing, I saw that the swiss cross at the center of the QRCode was not displayed. The base64 cross image is broken, that's why it's not displayed correctly. 
I used `'data:image/jpg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wgARCAAuAC4DAREAAhEBAxEB/8QAGgAAAgMBAQAAAAAAAAAAAAAAAAkHCAoGBf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhADEAAAAM/4DHCISoIABsFKAGfkBjg+kt2cCQEZVSYxpA3wgEoCI2OCA2ClADPyAAS4eAcEB//EADkQAAADBgUABQkJAQAAAAAAAAIDBgEEBQcIEgAJERMUChAadJcgMzU5WFm2xdUVFhciIzI0QmJk/9oACAEBAAE/AOqhXowOYFmDUqJSr+Ss0JSQ9MLAD42GOamj8SIfgcZ9Pcx7oCYcaBmpjuPTQbcZqWSpVblCEIY+plaoKMMX44kyC/cmLPj1tcHi729yXR3t15ZVtt3k9GD9RhIru6h+I4njpy/oumPvCy+SdfRgKFaVMwbMCVElav5UgWCYh0pIhGXOGDjD642PxcShhIDr3M4obdC3g5lt1uOzCZGHsKkeISj+oYpkpkkfRzI6B0303oZibRabY8MgsFBEHl6Y7MPeTXk39V5MMNHcccYP8w26XaMxW9ljUN5jxSZJrQkYBaBRzXxqbvUMRcOG162d/wDhPBN9/GJ/fdpZjswmRh7CpHiEo/qGK/JaIiTFd07JOyzgbIYm0nNtSQZPw3fMN4ji6xR5IIJvNEIY7SywBuGJom6atbjJTzUiMoOq2N1MnyMHMFkYQT2m/sUClZCtrefHJ5397jn66cO2yz++O3Lwv3Yx/jIz6RjLFrfKzHqG0NWiTLNqOCtARATE22Mc/h8WIvTl5/ZJ3LuNf5sOl+mM8TPFdcmF1lk8vNMo5j/iMOMhZYsWQjgcDhf8jxu38z/NtmO3Lwv3Yx/jIz6RiqmdrKlqoJkVHATTYMyYC9jCkZB2vnI4POfTnrY3bAbtm7bfaG7TW1nX0YP1GEiu7qH4jieOnL+i6Y+8LL5J5Ms6/K75MIhxlnJytebaTTcM3GQ1PpqZEUcHF0vMGaPaIIPCWC4wYxttYzUQ2txOyqqqCpZkNBUdUgvZgMg282DsWywfYrwd2zd2eUaPav2y7rdLrA69f//EABQRAQAAAAAAAAAAAAAAAAAAAFD/2gAIAQIBAT8AE//EABQRAQAAAAAAAAAAAAAAAAAAAFD/2gAIAQMBAT8AE//Z'` instead and it's working. I'm sure this image can be reduce a lot!

**Comment by thegnuu** [comment]
Hi @thibaultM42 

Hm, this really weird and I hate to say it, but it works on my machine ;)
We are using our library on AWS Lambda as well and on there the image is generated as expected...

Here are two images I just generated with the current tests within the master branch on my MacBook:

![bill-spec-ts-qr-bill-should-create-bills-in-a-6-without-lines-1-snap](https://user-images.githubusercontent.com/5129086/117115142-002ee780-ad8d-11eb-9c6d-f12f13fa9d69.png)

![test](https://user-images.githubusercontent.com/5129086/117115687-c01c3480-ad8d-11eb-972c-d5da93d461c1.png)


Can you tell me a bit more about the environment you are using to generate the code?

Cheers!

**Comment by thibaultM42** [comment]
No problem! :)

I just tried a little more, I'm also on Mac, in our project it's generated direclty in the browser,  in a React component. I tried it with Firefox and I didn't have the cross. But yes it's working on Chrome.

Perhaps the canvas element is not accepting this image in svg/base64 on FF. Or perhaps it's just on my version :). Feel free to close the issue if you don't want to support FF. Thanks for your time!

**Comment by thegnuu** [comment]
I'm using FF as well for most of my work but to be honest I was to lazy to check it in all Browsers for the last releases.
I think the library should support all major browsers, at least the latest version or so.

The best thing would be to add some browser-tests, but I am not really used to implement some kind of cross-browser tests.

The main reason why I switched to an SVG is to prevent the image from getting blurry, which was the case with the PNG or JPG images I uses prior to the SVG.

A quick DuckDuckGo session showed me this one: https://stackoverflow.com/a/28692538

Do you have the change to test it with an SVG which has the width and height property set since you already have a working test environment?

The image is currently rendered with 40 width an height.

You can find the original files I uses here: https://www.paymentstandards.ch/de/shared/communication-grid/swiss-qr-code.html

**Comment by thibaultM42** [comment]
Hi! @thegnuu 
Sorry for the long delay, I didn't test more with the SVG format as it was not working, but I used the official image you provide and transform it in base64. There is no blur for me on Chrome/FF. But I had to change a little bit the code as the swiss cross sometimes not showing (on FF and Chrome), perhaps it's due to my refactor, but it should be a safe improvement also for your lib do to like so:

```
  const swissCrossImage =
    ' data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKYAAACmAQMAAABqRmY0AAAABlBMVEUAAAD///+l2Z/dAAAARklEQVRIx2P4jwX8GYmiHxjQgf2o6PAU5QfG+IFR0VHRISgKFIGDA6Oio6LUFR1UaX1UdFSUBNFB2dYYFR3GooOh3zLwogCdq/PILxj57wAAAABJRU5ErkJggg=='
...
   imageObj.src = swissCrossImage
    imageObj.width = imgDim.width
    imageObj.height = imgDim.height
    imageObj.onload = () => {
      context?.drawImage(
        imageObj,
        canvasElement.width / 2 - imgDim.width / 2,
        canvasElement.height / 2 - imgDim.height / 2,
        imgDim.width,
        imgDim.height
      )
    }
```

`imageObj.onload()` will prevent to draw the image if it's not yet loaded. It was the case sometimes

**Comment by thegnuu** [comment]
Hi @thibaultM42 

Sorry it took me ages to look into this.
I update the library just now with some changes that should now work properly and in every case with Chrome, FF and Node.js. I updated PDFKit as well, which does not seem to work on Node.js 12 anymore, but I guess this should not be an issue, but that's why I created a new major version.
